name: librechat

networks:
  librechat_network:
  reverse_proxy_network:
    external: true

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

volumes:
  mongodb_data:
  meilisearch_data:
  librechat_images:
  librechat_uploads:
  librechat_logs:

services:
  api:
    image: ghcr.io/danny-avila/librechat:latest
    restart: always
    logging: *default-logging
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - ALLOW_REGISTRATION=false
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - librechat_images:/app/client/public/images
      - librechat_uploads:/app/uploads
      - librechat_logs:/app/api/logs
    networks:
      - librechat_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    restart: always
    logging: *default-logging
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth
    networks:
      - librechat_network

  meilisearch:
    image: getmeili/meilisearch:v1.35.1
    restart: always
    logging: *default-logging
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - librechat_network
