networks:
  internal-network:
  reverse_proxy_network:
    external: true

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

volumes:
  open-webui:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    restart: always
    logging: *default-logging
    volumes:
      - open-webui:/app/backend/data
    networks:
      - internal-network
      # Allow access from reverse proxy as application entrypoint
      - reverse_proxy_network
